name: apache-solr
version: 1
summary: Solr Search Platform
description: Solr is the popular, open source enterprise search platform built on Apache Lucene
confinement: strict
architectures: [all]

apps:
    solr:                                                               
        command: bin/run-solr
        daemon: simple                                                              
        plugs: [network-bind]
parts:
    solr:
        plugin: dump
        source: http://archive.apache.org/dist/lucene/solr/5.3.2/solr-5.3.2.tgz
    scripts:
        plugin: copy
        stage-packages:
            - unzip
            - openjdk-8-jre
            - lsof
        files:
            bin/run-solr: bin/run-solr
